# env
use_cpu: False
kvstore: local

# task is either [cls_ssg, cls_msg, seg]
task: seg
model_dir: output
# this is for both loading pretrained model in training and loading final model for testing
# set load_model_epoch to 0 to disable loading pretrained model
load_model_prefix: output/near555_8192/2019_10_19_15:28:58/near555_8192
load_model_epoch: 0
hash: para
# train
num_epochs: 2000
display_interval: 20
checkpoint_interval: 10
momentum: 0.9
lr_policy: step
lr_factor: 0.7
lr_factor_sample: 36000
#lr_factor_epochs: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
#small lr_factor_epochs: [50, 150,  250,  450,  650, 850]
lr_factor_epochs: [220,  510,  600, 700, 800, 900, 1000, 1100, 1200, 1400, 1600]
bn_decay_factor: 0.5
bn_decay_clip: 0.99
bn_decay_sample: 10000000
use_global_stats: False
beta1: 0.9
beta2: 0.999
#weight_decay: 0.00005
# per_class_weights: none, auto, manual
manual_weights:

# data
data_dir: ../data/scannet
#num_points: 8192
use_normal: False
input_dropout_ratio: 0

### aggregation # tucs    logs/near555_8192
###
###8192
###1024 cluster, 32pt / r 0.1, xyz_mlp=[32,32], mlp_list=[32,32,64]
###256  cluster, 32pt / r 0.2, xyz_mlp=[32,32], mlp_list=[64,64,128]
###64   cluster, 32pt / r 0.4, xyz_mlp=[32,32], mlp_list=[128,128,256]
###16   cluster, 32pt / r 0.8, xyz_mlp=[32,32], mlp_list=[256,256,512]
###
###64   cluster, interp , mlp_list=[256,256]
###256  cluster, interp , mlp_list=[256,256]
###1024 cluster, interp , mlp_list=[256,128]
###8192 cluster, interp , mlp_list=[128,128,128]
normalize: ball
use_bn: t
bn_decay: 0.9
aug_lv: 6
val_interval: 1
relutp: relu
optimizer: adam
weight_decay: 0.00001
per_class_weights: auto
aggtype: gcn
agg: max_pooling
fps: False
lr: 0.001
localfdim: 0
attfdim: 10
gpus: "3"
save_model_prefix: near555_8192
gcn_outDim: [[],[],[]]
voxel_size_lst: [[0.05, 0.05, 0.05], [0.133333,0.133333,0.133333], [0.4, 0.4, 0.4]]
grid_size_lst: [[40, 40, 40], [15, 15, 15], [5, 5, 5]]
lidar_coord: [1.0, 1.0, 1.0]
max_p_grid_lst: [64, 32, 32]
max_o_grid_lst: [1024, 256, 24]
kernel_size_lst: [3, 3, 3]
stride_lst: [1, 1, 1]
single_padding_lst: [none, none, none]
inputDim: [0, 64, 128]
elevation: []
cntxt_mlp_lst:
pt_ele_dim: [[32,32,64], [64,64,128], [128,128,256]]
relu: True
point_set: partial
batch_size: 12
loc_weight: True
loc_within: True
neigh_fetch: 0
att_full:

up_neigh_fetch: True
up_agg: max_pooling
up_aggtype: gcn
up_att_full:
up_type: grid
up_attfdim: 10
up_inputDim: [256, 128, 128]
up_voxel_size_lst: [[0.4, 0.4, 0.4], [0.133333,0.133333,0.133333], [0.05, 0.05, 0.05]]
up_grid_size_lst : [[5, 5, 5], [15, 15, 15], [40, 40, 40]]
up_max_p_grid_lst: [5, 5, 5]
up_max_o_grid_lst: [256, 1024, 8192]
up_kernel_size_lst: [3, 3, 3]
up_stride_lst: [1, 1, 1]
# add, concat
up_center_inte: concat
up_cntxt_mlp_lst:
up_center_dim: [[128], [128], [128]]
up_pt_ele_dim: [[128], [128], [128]]
up_gcn_outDim: [[128], [128], [128]]
num_points: 8192