######## GGCN 3 layers logs/ggcn_731_maxpooling_3_4_b16_330_1024_nopost_aug6_next_newdb_bgbgnet_gpall_bn90_slwlr_attcntxtfull_relu_continue
# group_all: False
# ##bn_decay_epochs: [60, 120, 200, 270]
# lr_factor_epochs: [200, 270]
# new: True
# bn_decay: 0.9
# postnorm: False
# normalize: ball
# augment_level: 6
# use_bn: t
# att_full: next
# inputDim: [0, 128, 256]
# gpus: "2"
# save_model_prefix: ggcn_731_maxpooling_3_4_b16_330_1024_nopost_aug6_next_newdb_bgbgnet_gpall_bn90_slwlr_attcntxtfull_relu_continue
# voxel_size_lst: [[0.05, 0.05, 0.05], [0.25, 0.25, 0.25], [2.0, 2.0, 2.0]]
# grid_size_lst: [[40, 40, 40], [8, 8, 8], [1, 1, 1]]
# lidar_coord: [1.0, 1.0, 1.0]
# max_p_grid_lst: [64, 64, 128]
# max_o_grid_lst: [1024, 128, 1]
# kernel_size_lst: [7, 3, 1]
# stride_lst: [1, 1, 1]
# single_padding_lst: [none, none, none]
# reverse_index: False
# fps: False
# aggtype: gcn
# localfdim: 3
# attfdim: 4
# elevation: []
# pt_ele_dim: [[64, 64, 128], [128, 128, 256], [256, 256, 512]]
# att_ele_dim: [[64, 128, 128], [128, 256, 256], [256, 512, 512]]
# cntxt_mlp_lst: [[],[],[]]
# gcn_outDim: [[],[],[]]
# relu: True
# agg: max_pooling
# point_set: full
# batch_size: 16
# loc_weight: True
# loc_within: True
# lr: 0.001



# # ######### GGCN 3 layers logs/ggcn_331_1632128_maxpooling_3_4_b16_330_1024_nopost_aug6_next_newdb_bgbgnet_gpall_bn90_slwlr_attcntxtfull_relu_40
# group_all: False
# ##bn_decay_epochs: [60, 120, 200, 270]
# lr_factor_epochs: [60, 120, 200, 270]
# new: True
# bn_decay: 0.9
# normalize: ball
# postnorm: False
# augment_level: 6
# use_bn: t
# att_full: next
# inputDim: [0, 128, 256]
# gpus: "2"
# save_model_prefix: ggcn_331_1632128_maxpooling_3_4_b16_330_1024_nopost_aug6_next_newdb_bgbgnet_gpall_bn90_slwlr_attcntxtfull_relu_40
# # voxel_size_lst: [[0.05, 0.05, 0.05], [0.25, 0.25, 0.25], [2.0, 2.0, 2.0]]
# # grid_size_lst: [[40, 40, 40], [8, 8, 8], [1, 1, 1]]
# voxel_size_lst: [[0.133333,0.133333,0.133333], [0.25, 0.25, 0.25], [2.0, 2.0, 2.0]]
# grid_size_lst: [[15, 15, 15], [8, 8, 8], [1, 1, 1]]
# lidar_coord: [1.0, 1.0, 1.0]
# max_p_grid_lst: [16, 32, 128]
# max_o_grid_lst: [1024, 128, 1]
# kernel_size_lst: [3, 3, 1]
# stride_lst: [1, 1, 1]
# single_padding_lst: [none, none, none]
# reverse_index: False
# fps: False
# aggtype: gcn
# localfdim: 3
# attfdim: 4
# elevation: []
# pt_ele_dim: [[64, 64, 128], [128, 128, 256], [256, 256, 512]]
# att_ele_dim: [[64, 128, 128], [128, 256, 256], [256, 512, 512]]
# cntxt_mlp_lst: [[],[],[]]
# gcn_outDim: [[],[],[]]
# relu: True
# agg: max_pooling
# point_set: full
# batch_size: 16
# loc_weight: True
# loc_within: True
# lr: 0.001