# env
use_cpu: False
kvstore: local
task: cls
model_dir: output
num_epochs: 330
display_interval: 20
checkpoint_interval: 30
val_interval: 1
optimizer: adam
momentum: 0.9
lr_policy: step
lr_factor: 0.7
bn_decay_factor: 0.5
bn_decay_clip: 0.99
use_global_stats: False
beta1: 0.9
beta2: 0.999
weight_decay: 0
#weight_decay: 0.000005
# per_class_weights: none, auto, manual
per_class_weights: none

# data
data_dir: ../data/
num_points: 1024
use_normal: False
input_dropout_ratio: 0
hash: para
relutp: relu

####### GGCN 3 layers logs
load_model_prefix: output/modelnet40
load_model_epoch: 0
group_all: False
lr_factor_epochs: [60, 120, 200, 270]
new: True
bn_decay: 0.9
normalize: ball
postnorm: False
augment_level: 6
use_bn: t
att_full: next
inputDim: [0, 128, 256]
gpus: "3"
save_model_prefix: modelnet40
voxel_size_lst: [[0.05, 0.05, 0.05], [0.25, 0.25, 0.25], [2.0, 2.0, 2.0]]
grid_size_lst: [[40, 40, 40], [8, 8, 8], [1, 1, 1]]
lidar_coord: [1.0, 1.0, 1.0]
max_p_grid_lst: [64, 64, 128]
max_o_grid_lst: [1024, 128, 1]
kernel_size_lst: [7, 3, 1]
stride_lst: [1, 1, 1]
single_padding_lst: [none, none, none]
reverse_index: False
fps: False
aggtype: gcn
localfdim: 3
attfdim: 4
elevation: []
pt_ele_dim: [[64, 64, 128], [128, 128, 256], [256, 256, 512]]
att_ele_dim: [[64, 128, 128], [128, 256, 256], [256, 512, 512]]
cntxt_mlp_lst: [[],[],[]]
gcn_outDim: [[],[],[]]
relu: True
agg: max_pooling
point_set: full
batch_size: 16
loc_weight: True
loc_within: True
lr: 0.001